### ISSUE TITLE
Esperanto flag icon not shown in menu bar

### ISSUE THREAD

**Issue by GuitarTab** [jakwings/mac-keyboard-Esperanto#4]
Instead, some sort of random pattern is shown.

*Flag_of_Esperanto.svg* and *Esperanto.iconset* are there.
![flagEOnono](https://user-images.githubusercontent.com/12575167/55288406-8c54d080-53b7-11e9-82c2-49b6e2f753ad.jpg)

**Comment by iology** [comment]
Hi, which version of mac os are you using?

The separate assets `*.svg` and `*.iconset` should not be included in the bundle. But btw, are they normally rendered in other places?

You can try to compile the icon locally:

* Download https://github.com/jakwings/mac-keyboard-Esperanto/archive/master.zip
* Unzip and go to the `assets` folder
* Click open `CompileIcon.command`
* In another tab, right-click `Esperanto.bundle` and show its content
* Replace Esperanto.bundle/Contents/Resources/*.icns with assets/Esperanto.icns
* Reinstall the bundle per instruction in ReadMe.txt

Please tell me if it works. You can also leave comments here (without email nor registration):

https://privatebin.net/?3991fb6b7e7ab4e3#WkAyG/nob7Ny1KniDYAIqOwdyfj5FM6ip5npGqlqsUs=

**Comment by GuitarTab** [comment]
Thanks for this fast response.

I'm on 10.13.6.

> The separate assets *.svg and *.iconset should not be included in the bundle.

OIC; they are there, **outside** the bundle.

There **are** icons within */Contents/Resources*, e.g. *Esperanto_US.icns*, and they depict a perfect Esperanto flag, but they are not displayed in the menu bar.

With some other *dvorak*.bundle layouts, there are no problems ...

**Comment by iology** [comment]
Also, do not put those assets files in `~/Library/Input Methods/`, I never tried that.

I guess the icon being broken is due to my crazy optimization on the icon size (no problem on 10.11.6 even after system reboot). Maybe the old ones are still okay.

**Comment by iology** [comment]
typo: `~/Library/Keyboard Layouts/` not `~/Library/Input Methods/`

Anyway those separate assets need not be installed anywhere. The latest Version 3.0.2 does not use optimized icons.
